"""Shared render-layer text and helpers so HTML, PDF, and Markdown agree.

Everything here is pure presentation: static disclaimer/caveat text and small
formatters over already-computed run_metadata. No canonical data is derived,
recomputed, or written back. The verification caveat is a single GENERIC
statement about the confidence scale — it never detects or names a specific
claim, allegation, or third party. The only company-specific value is the
subject company name, which is passed in from the report data.
"""

from datetime import datetime, timezone
from typing import Optional
from zoneinfo import ZoneInfo

# ── Generated-timestamp formatting ────────────────────────────────────────────
# Reports display the "Generated" time in US Eastern. The canonical
# ReportDocument keeps generated_at in UTC (correct for storage/interchange);
# this is a display-only conversion. America/New_York handles EST/EDT (daylight
# saving) automatically, and %Z renders the correct abbreviation.
_EASTERN = ZoneInfo("America/New_York")


def format_generated_et(dt: datetime) -> str:
    """Format a datetime as US Eastern, e.g. '2026-06-21 01:34 EDT'.

    Naive datetimes are assumed to be UTC (matching how generated_at is set).
    """
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(_EASTERN).strftime("%Y-%m-%d %H:%M %Z")


# ── Dash normalisation ────────────────────────────────────────────────────────
# House style: no "double dash" glyphs (em / en / figure / horizontal-bar /
# minus) anywhere in the rendered report. They are normalised to a single ASCII
# hyphen at render time. This is URL-safe — these glyphs never appear in URLs —
# and leaves ordinary ASCII hyphens and markdown "---" table syntax untouched.
_DASH_TABLE = {ord(c): "-" for c in "‒–—―−"}


def strip_dashes(text) -> str:
    """Replace em/en/figure/horizontal-bar/minus glyphs with a single hyphen."""
    return str(text).translate(_DASH_TABLE)


# ── Disclaimer + verification caveat ──────────────────────────────────────────

# One generic statement about what the confidence labels mean (NOT per-claim).
VERIFICATION_CAVEAT = (
    "Confidence labels reflect source-tier reliability, not independent "
    "verification; lower-confidence items, particularly allegations involving "
    "third parties, should be independently verified before any reliance."
)


def disclaimer_sentences(company_name: Optional[str]) -> list:
    """Return the disclaimer as a list of plain-text sentences.

    Generic for any company: the only interpolated value is the subject company
    name from the report data (falls back to a generic phrase if absent).
    """
    name = (company_name or "").strip() or "the subject company"
    # Avoid a double period when the legal name already ends in one (e.g. "Inc.").
    endorse = f"This report is not affiliated with, authorized by, or endorsed by {name}"
    endorse += "" if endorse.endswith(".") else "."
    return [
        "This report was generated by an automated multi-agent AI pipeline from "
        "public sources. It is a demonstration of that pipeline, not professional "
        "due diligence, and is not investment advice.",
        endorse,
        VERIFICATION_CAVEAT,
    ]


# ── Methodology fragments (shared so all three renderers match) ────────────────

_TIER_DISPLAY = {
    "primary_document":    "Primary (Tier 0)",
    "reputable_secondary": "Reputable (Tier 1)",
    "aggregator":          "Aggregator (Tier 2)",
    "community":           "Community (Tier 3)",
    "unknown":             "Unknown (Tier ?)",
}
_TIER_ORDER = ("primary_document", "reputable_secondary", "aggregator", "community", "unknown")


def tier_coverage_parts(tier_attempts: Optional[dict]) -> list:
    """Return ["Primary (Tier 0): NN%", ...] from raw per-tier source counts."""
    ta = tier_attempts or {}
    total = sum(ta.values())
    if total <= 0:
        return []
    parts = []
    for key in _TIER_ORDER:
        count = ta.get(key, 0)
        if count > 0:
            parts.append(f"{_TIER_DISPLAY.get(key, key)}: {round(count / total * 100)}%")
    return parts


def edgar_line(status: Optional[str], cik: Optional[str] = None) -> Optional[str]:
    """Return the EDGAR status line text, or None if no lookup was performed."""
    if not status:
        return None
    if status == "succeeded":
        return f"EDGAR: succeeded{f' (CIK: {cik})' if cik else ''}"
    return {
        "not_sec_reporting": "EDGAR: not SEC-reporting (private or non-US; expected)",
        "lookup_failed": "EDGAR: lookup failed; financial data from EDGAR unavailable",
        "rate_limited": "EDGAR: rate limited; financial data from EDGAR unavailable",
    }.get(status, f"EDGAR: {status}")
