"""
Schema drift test: the checked-in schema/report.schema.json must match what
ReportDocument.model_json_schema() produces. Run this after any model change;
regenerate the file with:

    python -c "import json; from src.schemas.models import ReportDocument; \
               print(json.dumps(ReportDocument.model_json_schema(), indent=2))" \
    > schema/report.schema.json
"""

import json
from datetime import datetime, timezone
from pathlib import Path

import pytest

from src.schemas.models import (
    AgentRunMetadata,
    Claim,
    ConfidenceLevel,
    GapRecord,
    ReportDocument,
    ReportFinancial,
    ReportResearch,
    ReportSynthesis,
    RunMetadata,
    SourceRef,
    SourceTier,
)

SCHEMA_FILE = Path(__file__).parent.parent / "schema" / "report.schema.json"


# ── Schema drift test ─────────────────────────────────────────────────────────

def test_schema_file_exists():
    assert SCHEMA_FILE.exists(), (
        "schema/report.schema.json not found. Regenerate with:\n"
        "  python -c \"import json; from src.schemas.models import ReportDocument; "
        "print(json.dumps(ReportDocument.model_json_schema(), indent=2))\" "
        "> schema/report.schema.json"
    )


def test_schema_properties_match_model():
    """Top-level properties in the schema file must match the live Pydantic model."""
    live = ReportDocument.model_json_schema()
    on_disk = json.loads(SCHEMA_FILE.read_text())
    live_props = set(live.get("properties", {}).keys())
    disk_props = set(on_disk.get("properties", {}).keys())
    assert live_props == disk_props, (
        f"Schema drift detected.\n"
        f"  In model but not in file: {live_props - disk_props}\n"
        f"  In file but not in model: {disk_props - live_props}\n"
        f"Regenerate schema/report.schema.json."
    )


def test_schema_defs_match_model():
    """All $defs in the schema must match those generated by the live model."""
    live = ReportDocument.model_json_schema()
    on_disk = json.loads(SCHEMA_FILE.read_text())
    live_defs = set(live.get("$defs", {}).keys())
    disk_defs = set(on_disk.get("$defs", {}).keys())
    assert live_defs == disk_defs, (
        f"Schema $defs drift.\n"
        f"  Added to model: {live_defs - disk_defs}\n"
        f"  Removed from model: {disk_defs - live_defs}"
    )


# ── Round-trip serialization ──────────────────────────────────────────────────

def _minimal_doc() -> ReportDocument:
    return ReportDocument(
        report_id="abc123def456",
        company_name="Stripe",
        generated_at=datetime(2026, 5, 17, 0, 0, 0, tzinfo=timezone.utc),
        run_metadata=RunMetadata(
            trace_id="abc123def456",
            cost_usd=0.45,
            duration_ms=9000.0,
            total_llm_calls=10,
            total_tool_calls=5,
            total_input_tokens=10000,
            total_output_tokens=2000,
            agents={
                "research": AgentRunMetadata(
                    llm_calls=3, tool_calls=2,
                    input_tokens=3000, output_tokens=600,
                    cost_usd=0.12, duration_ms=3000.0,
                ),
            },
        ),
        research=ReportResearch(
            description=Claim(
                claim_id="res001",
                field_name="description",
                value="Payment processor",
                confidence=ConfidenceLevel.HIGH,
                sources=[SourceRef(url="https://stripe.com", tier=SourceTier.UNKNOWN)],
                agent="research",
            ),
        ),
        gaps=[GapRecord(field="revenue", agent="financial", reason="Private company")],
    )


def test_roundtrip_json_serialization():
    """A ReportDocument serializes to JSON and deserializes without data loss."""
    doc = _minimal_doc()
    json_str = doc.model_dump_json()
    reloaded = ReportDocument.model_validate_json(json_str)
    assert reloaded.company_name == doc.company_name
    assert reloaded.report_id == doc.report_id
    assert reloaded.schema_version == doc.schema_version
    assert reloaded.run_metadata.trace_id == doc.run_metadata.trace_id
    assert reloaded.run_metadata.agents["research"].llm_calls == 3


def test_roundtrip_preserves_source_tier():
    doc = _minimal_doc()
    reloaded = ReportDocument.model_validate_json(doc.model_dump_json())
    assert reloaded.research.description.sources[0].tier == SourceTier.UNKNOWN


def test_roundtrip_preserves_synthesized_from():
    """synthesized_from survives JSON round-trip on a Claim."""
    doc = _minimal_doc()
    # Manually inject synthesized_from on the research description claim
    doc.research.description.synthesized_from = ["abc000111222"]
    reloaded = ReportDocument.model_validate_json(doc.model_dump_json())
    assert reloaded.research.description.synthesized_from == ["abc000111222"]


def test_roundtrip_preserves_gaps():
    doc = _minimal_doc()
    reloaded = ReportDocument.model_validate_json(doc.model_dump_json())
    assert len(reloaded.gaps) == 1
    assert reloaded.gaps[0].field == "revenue"
    assert reloaded.gaps[0].agent == "financial"


def test_schema_version_is_present():
    doc = _minimal_doc()
    assert doc.schema_version == "1.0.6"
